"""
Healthcare Intelligence Platform
Professional PDF Executive Report Generator

Creates a branded PDF directly from the live PostgreSQL warehouse
and AI summary generated by services.ai_summary.
"""

import os
from io import BytesIO
from datetime import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Spacer,
    Paragraph,
    Table,
    TableStyle,
    PageBreak
)

from database import get_engine
from services.ai_summary import generate_ai_report

engine = get_engine()

# ----------------------------------------------------------
# STYLES
# ----------------------------------------------------------

styles = getSampleStyleSheet()

TITLE = ParagraphStyle(
    "TITLE",
    parent=styles["Heading1"],
    fontSize=26,
    textColor=colors.HexColor("#0F172A"),
    alignment=TA_CENTER,
    spaceAfter=20
)

SUBTITLE = ParagraphStyle(
    "SUBTITLE",
    parent=styles["Heading2"],
    fontSize=14,
    textColor=colors.HexColor("#2563EB"),
    spaceAfter=10
)

SECTION = ParagraphStyle(
    "SECTION",
    parent=styles["Heading2"],
    fontSize=18,
    textColor=colors.HexColor("#1E40AF"),
    spaceAfter=12
)

BODY = ParagraphStyle(
    "BODY",
    parent=styles["BodyText"],
    fontSize=10,
    leading=18
)

SMALL = ParagraphStyle(
    "SMALL",
    parent=styles["BodyText"],
    fontSize=9,
    leading=14
)

# ----------------------------------------------------------
# DATABASE
# ----------------------------------------------------------

def query(sql):
    return pd.read_sql(sql, engine)


def warehouse_snapshot():

    kpi = query("""
    SELECT
        COUNT(*) total_patients,
        ROUND(SUM(billing_amount),2) total_revenue,
        ROUND(AVG(age),1) avg_age,
        ROUND(AVG(length_of_stay),1) avg_stay
    FROM fact_patients
    """)

    disease = query("""
    SELECT
        medical_condition,
        COUNT(*) patients,
        ROUND(AVG(billing_amount),2) avg_bill
    FROM fact_patients
    GROUP BY medical_condition
    ORDER BY patients DESC
    LIMIT 10
    """)

    hospital = query("""
    SELECT
        dh.hospital_name,
        COUNT(*) patients,
        ROUND(SUM(fp.billing_amount),2) revenue
    FROM fact_patients fp
    JOIN dim_hospital dh USING(hospital_id)
    GROUP BY dh.hospital_name
    ORDER BY revenue DESC
    LIMIT 10
    """)

    insurance = query("""
    SELECT
        di.insurance_provider,
        COUNT(*) claims,
        ROUND(SUM(fp.billing_amount),2) billing
    FROM fact_patients fp
    JOIN dim_insurance di USING(insurance_id)
    GROUP BY di.insurance_provider
    ORDER BY billing DESC
    """)

    doctors = query("""
    SELECT
        dd.doctor_name,
        COUNT(*) patients
    FROM fact_patients fp
    JOIN dim_doctor dd USING(doctor_id)
    GROUP BY dd.doctor_name
    ORDER BY patients DESC
    LIMIT 10
    """)

    return {
        "kpi": kpi,
        "disease": disease,
        "hospital": hospital,
        "insurance": insurance,
        "doctor": doctors
    }

# ----------------------------------------------------------
# TABLE BUILDER
# ----------------------------------------------------------

def dataframe_table(df):

    data = [list(df.columns)] + df.values.tolist()

    table = Table(data, repeatRows=1)

    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("GRID", (0,0), (-1,-1), .3, colors.grey),
        ("BACKGROUND", (0,1), (-1,-1), colors.HexColor("#F8FAFC")),
        ("BOTTOMPADDING", (0,0), (-1,0), 10),
        ("TOPPADDING", (0,1), (-1,-1), 8)
    ]))

    return table

# ----------------------------------------------------------
# COVER PAGE
# ----------------------------------------------------------

def cover(elements):

    elements.append(Spacer(1, 40))

    elements.append(
        Paragraph(
            "Healthcare Intelligence & Risk Analytics Platform",
            TITLE
        )
    )

    elements.append(
        Paragraph(
            "Enterprise Executive Intelligence Report",
            SUBTITLE
        )
    )

    elements.append(Spacer(1, 25))

    elements.append(
        Paragraph(
            f"""
            <b>Generated On:</b> {datetime.now().strftime("%d %B %Y")}<br/>
            <b>Platform:</b> Healthcare Intelligence Platform<br/>
            <b>Database:</b> PostgreSQL Healthcare Warehouse<br/>
            <b>Analytics:</b> Streamlit + SQL + Machine Learning + AI
            """,
            BODY
        )
    )

    elements.append(Spacer(1, 60))

    elements.append(
        Paragraph(
            """
            This report provides executive-level clinical, operational,
            financial and AI-powered healthcare insights generated from
            the live healthcare warehouse.
            """,
            BODY
        )
    )

    elements.append(PageBreak())

# ----------------------------------------------------------
# KPI PAGE
# ----------------------------------------------------------

def kpi_page(elements, kpi_df):

    k = kpi_df.iloc[0]

    elements.append(Paragraph("Executive KPI Overview", SECTION))

    metrics = [
        ["Metric","Value"],
        ["Total Patients", f"{int(k.total_patients):,}"],
        ["Total Revenue", f"${k.total_revenue:,.2f}"],
        ["Average Age", str(k.avg_age)],
        ["Average Stay", f"{k.avg_stay} Days"]
    ]

    table = Table(metrics, colWidths=[220,220])

    table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1D4ED8")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("BACKGROUND",(0,1),(-1,-1),colors.HexColor("#EFF6FF")),
        ("GRID",(0,0),(-1,-1),0.4,colors.grey),
        ("BOTTOMPADDING",(0,0),(-1,0),12)
    ]))

    elements.append(table)
    elements.append(PageBreak())

# ----------------------------------------------------------
# AI SUMMARY
# ----------------------------------------------------------

def ai_summary_page(elements):

    elements.append(Paragraph("AI Executive Healthcare Summary", SECTION))

    report = generate_ai_report(provider="Gemini")

    report = report.replace("\n","<br/>")

    elements.append(
        Paragraph(report, SMALL)
    )

    elements.append(PageBreak())

# ----------------------------------------------------------
# ANALYTICS PAGE
# ----------------------------------------------------------

def analytics_page(elements, snapshot):

    pages = [
        ("Top Diseases", snapshot["disease"]),
        ("Top Hospitals", snapshot["hospital"]),
        ("Top Doctors", snapshot["doctor"]),
        ("Insurance Performance", snapshot["insurance"])
    ]

    for title, df in pages:

        elements.append(Paragraph(title, SECTION))
        elements.append(dataframe_table(df))
        elements.append(Spacer(1,25))

    elements.append(PageBreak())

# ----------------------------------------------------------
# RECOMMENDATION PAGE
# ----------------------------------------------------------

def recommendation_page(elements):

    elements.append(Paragraph("Executive Recommendations", SECTION))

    bullets = [
        "Prioritize hospitals generating highest patient revenue.",
        "Monitor abnormal test results and long length-of-stay patients.",
        "Optimize insurance providers with high billing claims.",
        "Review medication utilization across top diseases.",
        "Continue AI risk prediction monitoring for proactive intervention.",
        "Use monthly revenue trends for operational planning.",
        "Expand staffing for hospitals with increasing admissions.",
        "Track chronic disease distribution quarterly."
    ]

    for item in bullets:
        elements.append(
            Paragraph(f"• {item}", BODY)
        )

    elements.append(PageBreak())

# ----------------------------------------------------------
# APPENDIX
# ----------------------------------------------------------

def appendix(elements):

    elements.append(Paragraph("Appendix", SECTION))

    elements.append(
        Paragraph(
            """
            Data Sources

            • Kaggle Healthcare Dataset (55,000+ Patients)

            • OpenFDA Adverse Drug Events API

            • PostgreSQL Healthcare Warehouse

            Machine Learning

            • Random Forest Risk Prediction Model

            ETL Pipeline

            • Python + PostgreSQL

            Dashboard Platform

            • Streamlit + Plotly
            """,
            BODY
        )
    )

# ----------------------------------------------------------
# MAIN FUNCTION
# ----------------------------------------------------------

def generate_pdf_report():

    snapshot = warehouse_snapshot()

    os.makedirs("reports", exist_ok=True)

    filename = (
        "reports/"
        f"Healthcare_AI_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    )

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=35,
        leftMargin=35,
        topMargin=35,
        bottomMargin=30
    )

    elements = []

    cover(elements)

    kpi_page(elements, snapshot["kpi"])

    ai_summary_page(elements)

    analytics_page(elements, snapshot)

    recommendation_page(elements)

    appendix(elements)

    doc.build(elements)

    return filename


if __name__ == "__main__":

    file = generate_pdf_report()

    print(f"Report Generated Successfully:\n{file}")